apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: ace-pipeline-taskrun-1
spec:
  serviceAccountName: ace-tekton-service-account
  taskRef:
    name: maven-ace-build
  params:
    - name: dockerRegistry
      value: "image-registry.openshift-image-registry.svc.cluster.local:5000"
