apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: ace-minimal-image-pipeline-run-1
spec:
  serviceAccountName: ace-tekton-service-account
  pipelineRef:
    name: ace-minimal-image-pipeline
  params:
    - name: dockerRegistry
      value: "image-registry.openshift-image-registry.svc:5000/default"
    - name: aceDownloadUrl
      value: "https://iwm.dhe.ibm.com/sdfdl/v2/regs2/mbford/Xa.2/Xb.WJL1CuPI9omKPzdPTNG0Am_d7-garN8eMjAwTUZAe8Y/Xc.12.0.8.0-ACE-LINUX64-DEVELOPER.tar.gz/Xd./Xf.lPr.D1vk/Xg.12291917/Xi.swg-wmbfd/XY.regsrvs/XZ.u9UUjbF2NL_1hwPFapkSedTVl2vYcpKK/12.0.8.0-ACE-LINUX64-DEVELOPER.tar.gz"
