apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: ace-minimal-image-pipeline-run-1
spec:
  serviceAccountName: ace-tekton-service-account
  pipelineRef:
    name: ace-minimal-image-pipeline
  params:
    - name: dockerRegistry
      value: "image-registry.openshift-image-registry.svc.cluster.local:5000/default"
    - name: aceDownloadUrl
      value: "https://iwm.dhe.ibm.com/sdfdl/v2/regs2/mbford/Xa.2/Xb.WJL1CuPI9omKj5inyv9-ir8PMDDUU8v2iYo-Oc5KPVI/Xc.12.0.4.0-ACE-LINUX64-DEVELOPER.tar.gz/Xd./Xf.lPr.D1vk/Xg.12260000/Xi.swg-wmbfd/XY.regsrvs/XZ._4mLAwxEK3xwdP7B6oAhifJgsNyp-ePc/12.0.4.0-ACE-LINUX64-DEVELOPER.tar.gz"
