# CI build to validate PR changes before merging

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: 
      image: tdolby/experimental:ace-minimal-12.0.4.0-alpine
      options: -u 0
      env:
        LICENSE: accept
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Install gradle
        run: |
          # ace-minimal doesn't have gradle so we install it here.
          
          # LD_LIBRARY_PATH includes glibc to make ACE work but that
          # breaks apk so we unset it.
          unset LD_LIBRARY_PATH || /bin/true
          apk add gradle
          
      - name: Build the application and test it
        shell: bash
        run: |
          # This shell has mqsiprofile already loaded
          echo "Running Gradle build and unit test"
          gradle -PCLASSPATH=$CLASSPATH
